# Generated by Django 6.0.6 on 2026-06-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone_number',
        ),
    ]
