# Generated by Django 5.1.4 on 2026-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
