# Generated by Django 5.1.4 on 2026-07-04 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctorprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')]),
        ),
    ]
