# Generated by Django 5.1.4 on 2026-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctorprofile_phone_number_and_more'),
        ('accounts', '0008_alter_patientprofile_national_id'),
    ]

    operations = [
    ]
