# Generated by Django 5.1.4 on 2026-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
