# Generated by Django 5.1.4 on 2026-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260707_1652'),
        ('appointments', '0002_doctoravailability_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_appointment_per_doctor_slot'),
        ),
    ]
